spring:
  main:
    banner-mode: log
  application:
    name: App
  profiles:
    active: BENCH

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      atlas:
        enabled: false

---
spring:
  profiles: BENCH
server:
      port: 8080




